window.REPOS = [
  {
    "name": "ebook_cloud",
    "description": null,
    "date": "2026-08-13",
    "stars": 0,
    "commits": 20,
    "lang": "HTML",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "loggia-worker-email",
    "description": null,
    "date": "2026-08-02",
    "stars": 0,
    "commits": 85,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "loggia",
    "description": null,
    "date": "2026-07-31",
    "stars": 0,
    "commits": 158,
    "lang": "TypeScript",
    "private": false,
    "url": "https://github.com/eeruwang/loggia",
    "live": null
  },
  {
    "name": "cloud-hollo",
    "description": null,
    "date": "2026-07-23",
    "stars": 0,
    "commits": 131,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "Hollo-Cloudflare",
    "description": null,
    "date": "2026-07-20",
    "stars": 0,
    "commits": 38,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "Everyeightyseconds_gallery",
    "description": null,
    "date": "2026-07-11",
    "stars": 0,
    "commits": 47,
    "lang": "HTML",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "ghost-themes",
    "description": null,
    "date": "2026-06-24",
    "stars": 0,
    "commits": 194,
    "lang": "CSS",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "everyday-digest",
    "description": null,
    "date": "2026-06-23",
    "stars": 0,
    "commits": 8,
    "lang": "HTML",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "readingunion",
    "description": null,
    "date": "2026-06-14",
    "stars": 0,
    "commits": 125,
    "lang": "HTML",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "google-website-builder",
    "description": null,
    "date": "2026-06-08",
    "stars": 0,
    "commits": 86,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "atmoment",
    "description": null,
    "date": "2026-05-19",
    "stars": 0,
    "commits": 11,
    "lang": "JavaScript",
    "private": true,
    "url": null,
    "live": "https://atmoment.eeruwang.me"
  },
  {
    "name": "eeruwangreading",
    "description": null,
    "date": "2026-05-16",
    "stars": 0,
    "commits": 28,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "whoiseeruwang",
    "description": null,
    "date": "2026-05-09",
    "stars": 0,
    "commits": 61,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": "https://whoiseeruwang.vercel.app"
  },
  {
    "name": "ghostsky",
    "description": null,
    "date": "2026-03-29",
    "stars": 0,
    "commits": 97,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": "https://ghostsky.vercel.app"
  },
  {
    "name": "Film-Review",
    "description": null,
    "date": "2026-03-06",
    "stars": 0,
    "commits": 295,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "directus-diary",
    "description": null,
    "date": "2026-03-03",
    "stars": 0,
    "commits": 28,
    "lang": "JavaScript",
    "private": true,
    "url": null,
    "live": "https://directus-diary.vercel.app"
  },
  {
    "name": "ghostship",
    "description": null,
    "date": "2026-02-11",
    "stars": 0,
    "commits": 148,
    "lang": "JavaScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "starship",
    "description": "여러 Fediverse 계정을 한 곳에서 관리하는 대시보드입니다.",
    "date": "2026-02-06",
    "stars": 1,
    "commits": 289,
    "lang": "JavaScript",
    "private": false,
    "url": "https://github.com/eeruwang/starship",
    "live": "https://starship.eeruwang.me"
  },
  {
    "name": "byongari-doc",
    "description": null,
    "date": "2025-10-29",
    "stars": 0,
    "commits": 20,
    "lang": "Astro",
    "private": false,
    "url": "https://github.com/eeruwang/byongari-doc",
    "live": "https://notice.byongari.com"
  },
  {
    "name": "Simple_eeruwang_blog",
    "description": null,
    "date": "2025-08-29",
    "stars": 0,
    "commits": 217,
    "lang": "TypeScript",
    "private": false,
    "url": "https://github.com/eeruwang/Simple_eeruwang_blog",
    "live": "https://simple-eeruwang-blog.vercel.app"
  },
  {
    "name": "diary",
    "description": null,
    "date": "2025-03-11",
    "stars": 0,
    "commits": 60,
    "lang": "TeX",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "eeruwang",
    "description": null,
    "date": "2024-03-02",
    "stars": 1,
    "commits": 93,
    "lang": "MDX",
    "private": true,
    "url": null,
    "live": "https://eeruwang.me"
  },
  {
    "name": "film-diary",
    "description": null,
    "date": "2024-02-23",
    "stars": 0,
    "commits": 3,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": "https://film-diary-tawny.vercel.app"
  },
  {
    "name": "writings",
    "description": null,
    "date": "2024-02-10",
    "stars": 0,
    "commits": 69,
    "lang": "MDX",
    "private": true,
    "url": null,
    "live": "https://writings-vert.vercel.app"
  },
  {
    "name": "dailiness",
    "description": null,
    "date": "2024-02-07",
    "stars": 0,
    "commits": 22,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": "https://dailiness.vercel.app"
  },
  {
    "name": "obsidian-backup",
    "description": null,
    "date": "2023-03-08",
    "stars": 0,
    "commits": 9,
    "lang": "JavaScript",
    "private": true,
    "url": null,
    "live": null
  },
  {
    "name": "archive",
    "description": null,
    "date": "2023-02-25",
    "stars": 0,
    "commits": 2083,
    "lang": "Astro",
    "private": true,
    "url": null,
    "live": "https://a.eeruwang.me"
  },
  {
    "name": "eeruwang-doc",
    "description": null,
    "date": "2023-01-01",
    "stars": 1,
    "commits": 117,
    "lang": "TypeScript",
    "private": true,
    "url": null,
    "live": "eeruwang-doc.vercel.app"
  }
]
;
